// <auto-generated />
using System;
using EtteplanMORE.ServiceManual.ApplicationCore.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EtteplanMORE.ServiceManual.ApplicationCore.Migrations
{
    [DbContext(typeof(FactoryContext))]
    [Migration("20200126180515_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EtteplanMORE.ServiceManual.ApplicationCore.Entities.FactoryDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("FactoryDevices","ServiceManual");
                });

            modelBuilder.Entity("EtteplanMORE.ServiceManual.ApplicationCore.Entities.MaintenanceTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Criticality");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<sbyte>("Done")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TINYINT(4)")
                        .HasDefaultValue((sbyte)0);

                    b.Property<int>("FactoryDeviceId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("FactoryDeviceId");

                    b.ToTable("MaintenanceTasks","ServiceManual");
                });

            modelBuilder.Entity("EtteplanMORE.ServiceManual.ApplicationCore.Entities.MaintenanceTask", b =>
                {
                    b.HasOne("EtteplanMORE.ServiceManual.ApplicationCore.Entities.FactoryDevice", "FactoryDevice")
                        .WithMany()
                        .HasForeignKey("FactoryDeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
